public abstract class Meter {

    private int consumed;
    private int generated;
    private boolean generating;

    public Meter(int startingValueConsumed, boolean canGenerate){
        consumed = startingValueConsumed;
        generating = canGenerate;
    }

    //don't use these methods as inefficient to use for loop
    public void incrementConsumed(){
        consumed++;
    }

    //adds amountToIncrement to consumed, throwing exception if amountToIncrement is negative
    public void incrementConsumed(int amountToIncrement) throws Exception{
        if(amountToIncrement >= 0) {
            consumed += amountToIncrement;
        }else{
            throw new Exception("Attempted to increment consumed on "+getType()+" meter by a negative amount!");
        }
    }

    //don't use these methods as would be inefficient to use for loop as opposed to +=
    //throws an exception if meter cannot generate but this method is called
    public void incrementGenerated() throws Exception{
        if(canGenerate()) {
            generated ++;
        }else{
            throw new Exception("This "+getType()+" meter cannot generate!");
        }
    }

    //increments generated by amountToIncrement
    //throws an exception if this method is called on a meter which cannot generate
    public void incrementGenerated(int amountToIncrement) throws Exception{
        if(canGenerate()) {
            generated += amountToIncrement;
        }else{
            throw new Exception("This "+getType()+" meter cannot generate!");
        }
    }

    //returns if the meter can generate
    Boolean canGenerate(){
        return generating;
    }

    //returns the integer consumed
    Integer getConsumed(){
        return consumed;
    }

    //return the integer generated
    public Integer getGenerated(){
        return generated;
    }

    //overridden in specific meters to give types
    abstract String getType();

}
